name = "dor-progress"
main = "src/worker.ts"
compatibility_date = "2025-05-01"
compatibility_flags = ["nodejs_compat"]

[vars]
APP_ENV = "production"
version = "1.0.411"
[[kv_namespaces]]
binding = "TRANSLATION_KV"
id = "d032e134adec47ab85ea1b5a8c18caab"

[[kv_namespaces]]
binding = "REPORTS_KV"
id = "d8701afe5c9b49159942de3049bb4af0"